export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const GET_MARKETS_REQUEST = 'GET_MARKETS_REQUEST';
export const GET_MARKETS_SUCCESS = 'GET_MARKETS_SUCCESS';
export const GET_MARKETS_FAILURE = 'GET_MARKETS_FAILURE';
export const USERNAME_CHANGE = 'USERNAME_CHANGE';
export const LOGOUT = 'LOGOUT';
